### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kitchung** [jakowenko/double-take#123]
**Describe the bug**
Stuck in "Training" with no progress if a HEIF image was uploaded.

**Version of Double Take**
`v1.3.0-5fdac97`

**Expected behavior**
Failed detection should be purged from the database, restrict unsupported file types or convert it to a supported file type.

**Screenshots**
N/A

**Hardware**
 - OS: N/A
 - Browser (if applicable) [e.g. Chrome, Safari]: N/A

**Additional context**
Very impressive app!

**Comment by jakowenko** [comment]
Thank you for reporting this. Do you have a sample file that produces this error I could use to test with?

**Comment by kitchung** [comment]
This may have been the log entry:

`error: TypeError: Cannot convert undefined or null to object                    
     at /double-take/api/src/controllers/train.controller.js:44:7
     at Array.forEach (<anonymous>)
     at /double-take/api/src/controllers/train.controller.js:42:15
     at Array.forEach (<anonymous>)
     at module.exports.get (/double-take/api/src/controllers/train.controller.js:39:9)
     at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
     at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
     at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
     at /double-take/api/src/middlewares/index.js:42:5
     at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)`

**Comment by kitchung** [comment]
i shell'd into the container, installed sqlite and used sqlite3 with the following commands:

`select * from train;`
and found the following entry:
`866||||deepstack|{"message":"Cannot read property 'name' of undefined","status":500,"detector":"deepstack"}|2021-10-09T23:59:28.791Z`
I got rid of the stuck training by running the following command:
`delete from train where ID = 866;`
