### ISSUE TITLE
[FEAT] Cannot connect multiple instances

### ISSUE THREAD

**Issue by Salvora** [jakowenko/double-take#134]
**Describe the bug**
I wanted to add another detector to the DT but when I add it, it loses all the connection of deepstack detectors.

config:
This is currently working.
```yaml
detectors:
  deepstack:
    url: http://192.168.1.41:9776
    key: "sdg34341222fdSAS6"
    # number of seconds before the request times out and is aborted
    timeout: 30
```
But if I add another detector:
```
detectors:
  deepstack:
    url: http://192.168.1.41:9776
    key: "sdg34341222fdSAS6"
    # number of seconds before the request times out and is aborted
    timeout: 30
    
  deepstack_gs60:
    url: http://192.168.1.72:9540
    key: "sdg34341222fdSAS6"
    # number of seconds before the request times out and is aborted
    timeout: 30
```
Both of them go down. Does it not support multiple detectors of the same type?
**Version of Double Take**
1.5.0

**Expected behavior**
It should connect at least one of them with no problem since I know that one of them definetely works.

**Screenshots**

**Hardware**
 - Synology Docker

**Additional context**
I see the below in the logs.
```
21-10-19 18:42:46 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:42:54 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:42:57 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:43:18 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:43:48 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:44:18 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:44:48 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:45:19 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:45:49 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:46:19 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:46:49 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:47:20 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:47:50 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:47:51 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:48:20 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:48:22 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:48:38 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:48:50 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:49:08 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:49:20 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:49:39 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
21-10-19 18:49:51 error: TypeError: Cannot read property 'recognize' of undefined
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:3:72)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:19:5)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)
```

**Comment by wonkydog** [comment]
Hi David,

Great project and a very interesting use case that's mentioned here.

I really don't want to take away from the OP or what they are trying to achieve but would multiple instances in this sense help with 'Still processing previous request' log messages.

To give some further detail, I have multiple raspberry pi 4 running deepstack and I would like to configure two or more detectors for face recognition. Ideally I would like to train all instances symmetrically but when processing, share or distribute the load. 

Hopefully reducing the 'Still processing' messages.

Thanks all, and David really enjoying the work so far. A few months ago my cameras were very dumb but given Frigate and now Double Take I'm now getting some great detail. Double Take is a very interesting project and I'm really excited to see where it goes!

WD
