### ISSUE TITLE
Js null on foreach exception

### ISSUE THREAD

**Issue by Sangoku** [jakowenko/double-take#165]
**Describe the bug**
When selecting pictures to be trained, you get a js error. 

**Version of Double Take**
Double Take
Current version: 1.6.0
Home assistant add-on

 This is the error which is happening in the logs. 
```
21-11-18 18:45:23 info: {
  id: '0c7ac5a5-959d-463d-bbcd-d129e52e18f7',
  duration: 0.29,
  timestamp: '2021-11-18T17:45:23.245Z',
  attempts: 1,
  camera: 'front_door',
  zones: [],
  matches: [],
  misses: []
}
21-11-18 19:22:17 info: medo: queuing 8 file(s) for training
21-11-18 19:22:21 error: TypeError: Cannot convert undefined or null to object
    at /double-take/api/src/controllers/train.controller.js:44:7
    at Array.forEach (<anonymous>)
    at /double-take/api/src/controllers/train.controller.js:42:15
    at Array.forEach (<anonymous>)
    at module.exports.get (/double-take/api/src/controllers/train.controller.js:39:9)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at /double-take/api/src/middlewares/index.js:42:5
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
21-11-18 19:22:22 info: medo: training complete in 9.8 sec
```
 

**Hardware**
 - OS: Debian
 - Browser Chrome

**Additional context**

**Comment by jakowenko** [comment]
Can you post your Double Take config?

**Comment by Sangoku** [comment]
Sure |:D
 

`auth: false
detect:
  match:
    save: true
    base64: false
    confidence: 60
    purge: 168
    min_area: 10000
  unknown:
    save: true
    base64: false
    confidence: 40
    purge: 8
    min_area: 0
time:
  timezone: UTC
frigate:
  attempts:
    latest: 10
    snapshot: 10
    mqtt: true
    delay: 0
  image:
    height: 500
  labels:
    - person
  url: http://xxx.xxx.xxx.xxx:5005
mqtt:
  topics:
    frigate: frigate/events
    matches: double-take/matches
    cameras: double-take/cameras
    homeassistant: homeassistant
  host: xxx.xxx.xxx.xxx
  user: xxxxx
  password: xxx
logs:
  level: info
ui:
  theme: bootstrap4-dark-blue
  editor:
    theme: twilight
  logs:
    lines: 500
  pagination:
    limit: 50
  thumbnails:
    quality: 95
    width: 500
detectors:
  deepstack:
    timeout: 15
    url: http://xxx.xxx.xxx.xxx:5001
  facebox:
    timeout: 15
    url: http://xxx.xxx.xxx.xxx:8000
server:
  port: 3000
storage:
  path: /config/double-take
  config:
    path: /config/double-take
  media:
    path: /media/double-take
  tmp:
    path: /dev/shm/double-take
version: 1.6.0-893328f`
