### ISSUE TITLE
[BUG] error: TypeError: Cannot read properties of undefined (reading 'recognize')

### ISSUE THREAD

**Issue by bigbangus** [jakowenko/double-take#180]
**Describe the bug**
double-take won't connect to CompreFace gpu versions despite the Compreface GUI working and processing images. I have 3 versions of compreface working each on separate external db's and separate ports (8800,8810,8820). If I change my double-take config to the gpu url and api key it just won't connect and then timeout. If I switch back to the regular version of compreface url and api key. It turns green and works fine.

**Version of Double Take**
1.7.0

**Expected behavior**
double-take log:
21-12-20 09:54:17 error: TypeError: Cannot read properties of undefined (reading 'recognize')
    at Object.module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:4:24)
    at module.exports.test (/double-take/api/src/controllers/recognize.controller.js:30:10)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:11:14)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/double-take/api/node_modules/express/lib/router/route.js:112:3)

**Hardware**
 - OS: Unraid 6.10-rc2
 - Chrome Latest

**Comment by bigbangus** [comment]
in the docker log of compreface gpu mobilenet, it floods with messages when double-take tries to connect:
`dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=418, y_min=318, x_max=445, y_max=352, probability=0.0003321561962366104, _np_landmarks=array([[425.90286, 331.558 ],\n [436.8255 , 332.08057],\n [430.7274 , 339.37637],\n [426.3802 , 345.40378],\n [434.853 , 345.77383]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=135, y_min=334, x_max=388, y_max=598, probability=0.0003245360858272761, _np_landmarks=array([[296.75464, 449.74524],\n [323.0665 , 448.194 ],\n [340.5085 , 487.16107],\n [280.48 , 506.53302],\n [310.37476, 506.41858]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=297, y_min=320, x_max=350, y_max=391, probability=0.0003220316139049828, _np_landmarks=array([[312.02948, 349.2632 ],\n [328.99036, 349.6571 ],\n [317.64297, 363.69095],\n [313.72913, 373.4362 ],\n [327.5487 , 373.57498]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=440, y_min=294, x_max=466, y_max=327, probability=0.0003163521469105035, _np_landmarks=array([[447.83432, 305.00055],\n [458.17163, 306.04117],\n [452.04276, 312.9299 ],\n [447.0442 , 319.01303],\n [455.1617 , 319.7975 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=432, y_min=303, x_max=446, y_max=319, probability=0.00031376746483147144, _np_landmarks=array([[436.2149 , 309.37595],\n [442.36322, 309.48877],\n [439.19592, 313.03003],\n [436.72797, 316.44226],\n [441.5365 , 316.5379 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=432, y_min=310, x_max=446, y_max=328, probability=0.0003135231963824481, _np_landmarks=array([[436.33777, 317.40814],\n [442.29385, 317.5169 ],\n [439.25385, 321.22308],\n [436.7862 , 324.76132],\n [441.46307, 324.86685]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=281, y_min=358, x_max=339, y_max=422, probability=0.0003131261619273573, _np_landmarks=array([[298.70285, 385.62518],\n [317.2772 , 386.91473],\n [305.81567, 398.60242],\n [302.25705, 406.55496],\n [316.39243, 407.2938 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=221, y_min=228, x_max=282, y_max=306, probability=0.0003026160120498389, _np_landmarks=array([[251.16289, 258.0566 ],\n [270.30905, 259.5606 ],\n [265.19034, 276.65524],\n [253.18652, 290.98703],\n [266.09686, 292.29453]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=468, y_min=193, x_max=530, y_max=265, probability=0.0003009444335475564, _np_landmarks=array([[485.19937, 223.0389 ],\n [503.90286, 224.30966],\n [490.29138, 240.68913],\n [487.0224 , 250.77686],\n [500.74945, 251.54105]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=440, y_min=279, x_max=467, y_max=311, probability=0.0002855696657206863, _np_landmarks=array([[446.91504, 290.69922],\n [459.6382 , 292.04446],\n [452.1216 , 298.87625],\n [445.8705 , 304.08148],\n [455.8997 , 305.1043 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=425, y_min=271, x_max=453, y_max=305, probability=0.0002810034202411771, _np_landmarks=array([[433.4304 , 284.80203],\n [444.96808, 284.40445],\n [439.49734, 292.5847 ],\n [435.17764, 298.57718],\n [444.61234, 298.26776]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=262, y_min=434, x_max=295, y_max=475, probability=0.00028004191699437797, _np_landmarks=array([[270.34158, 450.45 ],\n [282.53537, 450.34323],\n [275.5194 , 460.02054],\n [272.21255, 466.93112],\n [282.3522 , 466.75052]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=416, y_min=318, x_max=430, y_max=335, probability=0.000271462689852342, _np_landmarks=array([[420.176 , 324.63403],\n [426.43787, 324.7755 ],\n [423.1201 , 328.53784],\n [420.62674, 332.01154],\n [425.57733, 332.12064]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=424, y_min=302, x_max=438, y_max=319, probability=0.0002695881121326238, _np_landmarks=array([[428.01822, 309.27405],\n [434.00452, 309.35147],\n [430.862 , 312.8895 ],\n [428.5456 , 316.18112],\n [433.23907, 316.24615]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=116, y_min=15, x_max=142, y_max=47, probability=0.0002650227688718587, _np_landmarks=array([[123.55866 , 27.199055],\n [133.9365 , 26.954735],\n [128.84914 , 34.226562],\n [125.290695, 40.222416],\n [133.97485 , 39.94758 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=355, y_min=181, x_max=580, y_max=453, probability=0.00025376633857376873, _np_landmarks=array([[440.64746, 275.9206 ],\n [470.92047, 288.0431 ],\n [432.1566 , 332.86075],\n [427.79984, 369.36282],\n [449.5012 , 378.37842]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=277, y_min=391, x_max=344, y_max=456, probability=0.00025132379960268736, _np_landmarks=array([[301.64032, 420.21887],\n [314.45456, 422.41766],\n [305.01416, 431.90277],\n [303.63232, 437.21597],\n [313.35727, 438.58057]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=329, y_min=209, x_max=385, y_max=289, probability=0.0002468668681103736, _np_landmarks=array([[344.19876, 243.3545 ],\n [362.61993, 241.17734],\n [352.58417, 261.28226],\n [351.82785, 275.3031 ],\n [365.05624, 273.25732]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=295, y_min=374, x_max=357, y_max=439, probability=0.00024579002638347447, _np_landmarks=array([[316.83188, 405.41898],\n [331.1991 , 400.42044],\n [328.3878 , 414.35837],\n [331.13724, 424.109 ],\n [341.3721 , 419.83313]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=155, y_min=219, x_max=389, y_max=492, probability=0.00024097372079268098, _np_landmarks=array([[265.5984 , 308.549 ],\n [319.82654, 313.15656],\n [297.71634, 356.1645 ],\n [249.31233, 390.0966 ],\n [305.7244 , 395.03262]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=329, y_min=284, x_max=388, y_max=364, probability=0.00023663636238779873, _np_landmarks=array([[345.3217 , 311.48206],\n [363.61514, 313.1752 ],\n [350.0583 , 329.123 ],\n [347.16504, 342.7126 ],\n [361.8886 , 343.5451 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=-152, y_min=202, x_max=332, y_max=790, probability=0.00022212747717276216, _np_landmarks=array([[ 42.11737, 438.44638],\n [188.31674, 425.30234],\n [143.74762, 561.0838 ],\n [ 68.67941, 644.8337 ],\n [186.72145, 634.07385]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=206, y_min=304, x_max=258, y_max=378, probability=0.00021378396195359528, _np_landmarks=array([[231.0161 , 325.8772 ],\n [248.42789, 327.43518],\n [242.77316, 341.3203 ],\n [231.16846, 355.16998],\n [246.35931, 356.48523]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=-133, y_min=33, x_max=98, y_max=326, probability=0.0002058042009593919, _np_landmarks=array([[-52.63002 , 140.56665 ],\n [ 8.212009, 142.02217 ],\n [-19.829 , 192.08984 ],\n [-44.198357, 236.44626 ],\n [ 14.578291, 236.44687 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=316, y_min=254, x_max=371, y_max=336, probability=0.0002031730255112052, _np_landmarks=array([[321.31714, 282.47513],\n [342.53235, 283.66876],\n [324.0444 , 300.9041 ],\n [324.1523 , 315.877 ],\n [341.73233, 316.2775 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=424, y_min=310, x_max=438, y_max=328, probability=0.00019913469441235065, _np_landmarks=array([[428.04538, 317.35098],\n [434.23123, 317.4443 ],\n [430.97827, 321.23962],\n [428.54675, 324.7444 ],\n [433.37424, 324.83612]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=8, y_min=374, x_max=240, y_max=612, probability=0.00017853752069640905, _np_landmarks=array([[104.83275, 500.64893],\n [129.53622, 468.8887 ],\n [139.229 , 521.14185],\n [142.97047, 552.2245 ],\n [170.5137 , 525.2095 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=239, y_min=-11, x_max=476, y_max=284, probability=0.00017725482757668942, _np_landmarks=array([[340.86722, 112.68295],\n [358.32196, 119.92057],\n [332.026 , 175.23589],\n [328.5462 , 199.247 ],\n [339.9581 , 205.13828]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=425, y_min=287, x_max=453, y_max=321, probability=0.00017528902390040457, _np_landmarks=array([[432.27634, 299.837 ],\n [444.39124, 300.29907],\n [437.65005, 307.75058],\n [432.54865, 314.16528],\n [442.67856, 314.5169 ]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=206, y_min=244, x_max=262, y_max=324, probability=0.00016802256868686527, _np_landmarks=array([[230.19519, 272.615 ],\n [246.71465, 274.2426 ],\n [240.0477 , 289.2488 ],\n [232.81592, 305.61597],\n [245.62845, 306.95093]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version": "dev"}
{"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=418, y_min=303, x_max=444, y_max=337, probability=0.00010654756624717265, _np_landmarks=array([[423.88257, 315.3915 ],\n [436.05298, 315.89233],\n [429.0258 , 323.40042],\n [423.89075, 329.7114 ],\n [433.8108 , 330.13132]], dtype=float32))", "request": {"method": "POST", "path": "/find_faces", "filename": "lenna.jpg", "api_key": "", "remote_addr": "127.0.0.1"}, "logger": "src.services.facescan.plugins.insightface.insightface", "module": "insightface", "traceback": null, "build_version":`

**Comment by bigbangus** [comment]
detailed breakdown of issue on compreface page. @jakowenko please take a read if you can. I think this is a double-take issue and not a compreface issue because it works fine until I connect it to double-take?

https://github.com/exadel-inc/CompreFace/issues/691

**Comment by jakowenko** [comment]
Hey @bigbangus, thanks for letting me know about this. I've responded on the CompreFace issue and will keep an eye on it if there's something I need to update.

**Comment by bigbangus** [comment]
Appreciate it!

**Comment by bigbangus** [comment]
looks like the culprit is that you hard-coded the lenna.jpg status check with a det_prob_threshold = 0 which sends the compreface custom builds (gpu versions) into a frenzy trying to recognize thousands of faces.

If you can update the code to use 0.1 or the value set in the double-take config I believe that would solve the issue.

**Comment by bigbangus** [comment]
ok I just learned how to make a pull request and sent that your way. Thanks again for everything you've done. Sorry to pester you about this fix. I'm just excited to use compreface gpu versions!
