### ISSUE TITLE
[BUG] Masked images not deleted from TMP

### ISSUE THREAD

**Issue by Enc3ph4l0n** [jakowenko/double-take#208]
**Bug**
Mask images are not deleted from TMP. Eventually it runs out of space and crashes.

`Error: ENOSPC: no space left on device, write
    at Object.writeSync (node:fs:888:3)
    at Object.writeFileSync (node:fs:2176:26)
    at Object.module.exports.writer (/double-take/api/src/util/fs.util.js:66:6)
    at module.exports.polling (/double-take/api/src/util/process.util.js:50:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:148:7) {
  errno: -28,
  syscall: 'write',
  code: 'ENOSPC'
}`

**Expected**
Mask images should be deleted from TMP once processed.

**Code**
File: `double-take/api/src/util/process.util.js`

'Source' file is deleted here:

Line 80: `filesystem.delete(tmp.source);`

'Mask' file is created here if maskBuffer is set:

Line 48: ``tmp.mask =
            visible === true ? tmp.source : `${STORAGE.TMP.PATH}/${id}-${type}-${uuidv4()}.jpg`;
          filesystem.writer(tmp.mask, buffer);``

Mask file isn't deleted if created.

**Additional**
Files are removed from TMP on restart as expected.

**Comment by jakowenko** [comment]
Thank you for reporting this. I will dig into it tonight and try to get a fix out.

**Comment by jakowenko** [comment]
This should be fixed in `v1.10.0`. Thank you for catching it.
