### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'flatMap')

### ISSUE THREAD

**Issue by jarhed** [jakowenko/double-take#242]
**Describe the bug**
When uploading an image manually or when triggered by MQTT, I get this

`22-09-25 17:33:26 info: processing manual: 146050f2-98d4-4953-9aad-1f7558164230
22-09-25 17:33:26 error: TypeError: deepstack process error: Cannot read properties of undefined (reading 'flatMap')
    at Object.module.exports.normalize (/double-take/api/src/util/detectors/deepstack.js:68:39)
    at module.exports.normalize (/double-take/api/src/util/detectors/actions/index.js:8:25)
    at Object.module.exports.process (/double-take/api/src/util/process.util.js:163:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.module.exports.start (/double-take/api/src/util/process.util.js:142:17)
    at async module.exports.polling (/double-take/api/src/util/process.util.js:55:25)
    at async Promise.all (index 0)
    at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:152:7)
22-09-25 17:33:26 info: done processing manual: 146050f2-98d4-4953-9aad-1f7558164230 in 0.34 sec
22-09-25 17:33:26 info: {
  id: '146050f2-98d4-4953-9aad-1f7558164230',
  duration: 0.34,
  timestamp: '2022-09-25T16:33:26.842Z',
  attempts: 1,
  camera: 'manual',
  zones: [],
  matches: [],
  misses: []
}`

**Version of Double Take**
`v1.12.1-35874f3`

**Expected behavior**
I'm assuming it will look for faces in the image

**Screenshots**

**Hardware**
 - OS: Running HA OS in virtual box
 - Browser (if applicable) Firefox

**Comment by jarhed** [comment]
For anyone else that has this problem, it's because I had the wrong port. Should be 0.0.0.0:5001.

I'm an idiot

**Comment by jakowenko** [comment]
> For anyone else that has this problem, it's because I had the wrong port. Should be 0.0.0.0:5001.
> 
> 
> 
> I'm an idiot

Glad you got it working! I'll see if I can better catch the error and provide something more useful.
