### ISSUE TITLE
[BUG] not working with CompreFace 1.1.0

### ISSUE THREAD

**Issue by redwood996** [jakowenko/double-take#245]
**Describe the bug**
Not working with latest CompreFace 1.1.0

**Version of Double Take**
`1.2.1-35874f3`

**Expected behavior**
Works fine with CompreFace 1.0.1

**Screenshots**
`22-10-08 15:15:53 error: Error: compreface process error: Error during synchronization between servers: [500 INTERNAL SERVER ERROR] during [POST] to [http://compreface-core:3000/find_faces] [FacesFeignClient#findFaces(MultipartFile,Integer,Double,String)]: [{"message":"RuntimeError: simple_bind error. Arguments:\ndata: (1, 3, 480, 640)\nTraceback (most recent call last):\n  File \"../src/storage/./pooled_storage_manager.h\", line 160\nMXNetError: cudaMalloc retry failed: out of memory"}
]
    at Object.module.exports.normalize (/double-take/api/src/util/detectors/compreface.js:72:11)
    at module.exports.normalize (/double-take/api/src/util/detectors/actions/index.js:8:25)
    at Object.module.exports.process (/double-take/api/src/util/process.util.js:163:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.module.exports.start (/double-take/api/src/util/process.util.js:142:17)
    at async module.exports.reprocess (/double-take/api/src/controllers/match.controller.js:152:19)`

**Hardware**
 - HomeAssistant Supervised
 - Browser:Edge

**Additional context**

**Comment by redwood996** [comment]
never mind. Just find out the new version CompreFace needs more graphics memory, and I'm basically running of graphics memory.
