### ISSUE TITLE
[BUG] Unable to connect to Compreface

### ISSUE THREAD

**Issue by enjibby** [jakowenko/double-take#318]
**Describe the bug**

I have Double Take installed as an add-on to my Home Assistant OS on RPi, making use of frigate and compreface that are both remotely installed on a PC with access to a CUDA GPU.

I have recently updated the frigate and compreface stacks to their most recent versions (compreface 1.1.0, frigate 0.12.0) and the next time that Double Take restarted it is no longer able to communicate with Compreface i.e. the status dot beside Compreface in the config section is red rather than green.

**Version of Double Take**
`1.13.1-8e2728d`

**Expected behavior**
I expect that the status dot beside Compreface is green, signifying that Double Take can successfully connect.

**Screenshots**
The container log for Double Take contains the following exception:
```
error: Error: compreface process error: Something went wrong, please try again
    at Object.module.exports.normalize (/double-take/api/src/util/detectors/compreface.js:72:11)
    at module.exports.normalize (/double-take/api/src/util/detectors/actions/index.js:8:25)
    at Object.module.exports.process (/double-take/api/src/util/process.util.js:163:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.module.exports.start (/double-take/api/src/util/process.util.js:142:17)
    at async module.exports.polling (/double-take/api/src/util/process.util.js:55:25)
    at async Promise.all (index 0)
    at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:152:7)
```

**Hardware**
 - OS: Home Assistant 2023.6.1

**Additional context**
Honestly I'm hoping the exception report should give most of the required context, but please let me know if I need to supply more.

**Comment by Bug23451** [comment]
Do you have a api key in the config file?

I recall having a similar issue when I first set up compreface without a key.

**Comment by enjibby** [comment]
Yes, it is set up as it was before the update, the API key sitting in a secret file that (I've just checked now) remains the same as the API key currently listed in the compreface web UI. I've also just checked and, if I change the API key and refresh the config, it correctly shows a json message in the status mouseover that says that the key is incorrect.

**Comment by enjibby** [comment]
Digging further, I've used postman to reproduce the error directly in the compreface API. I guess this means it's clearly not a double-take issue! Thanks everyone.
