### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghallford** [jakowenko/double-take#332]
**Describe the bug**
Update_sub_labels back to Frigate not working

**Version of Double Take**
1.13.11.4

**Expected behavior**
Labels of found people go back to Frigate

**Hardware**
 - OS: Unraid / Docker

**Additional context**
Errors that appear in the logs:

```
info: done processing kitchen: 1696790604.57984-f12lzu in 2.46 sec
info: {
  id: '1696790604.57984-f12lzu',
  duration: 2.46,
  timestamp: '2023-10-08T18:43:34.989Z',
  attempts: 14,
  camera: 'kitchen',
  zones: [],
  counts: { person: 0, match: 1, miss: 0, unknown: -1 },
  matches: [
    {
      name: 'geoff',
      confidence: 90.83,
      match: true,
      box: [Object],
      type: 'snapshot',
      duration: 0.96,
      detector: 'compreface',
      filename: '72999012-a675-4a9d-874c-d804d13a65c0.jpg'
    }
  ],
  misses: [],
  unknowns: []
}
error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at /double-take/api/src/app.js:46:38
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at /double-take/api/src/app.js:46:38
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)

**Comment by Nafania** [comment]
Plus one. Have the same in the latest version

**Comment by timknowlden** [comment]
+1

`23-10-14 10:45:53 error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
    at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
    at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
    at /double-take/api/src/app.js:46:38
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
23-10-14 10:46:07 info: processing grace: 1697276747.701859-xsqi4b
23-10-14 10:46:09 info: done processing grace: 1697276747.701859-xsqi4b in 2.03 sec
23-10-14 10:46:09 info: {
  id: '1697276747.701859-xsqi4b',
  duration: 2.03,
  timestamp: '2023-10-14T09:46:09.994Z',
  attempts: 15,
  camera: 'grace',
  zones: [],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []`

**Comment by Shurov** [comment]
+1
