### ISSUE TITLE
[BUG] No connection to deepstack

### ISSUE THREAD

**Issue by AnduriI** [jakowenko/double-take#344]
**Describe the bug**
I have frigate, double-take and deepstack running on Truenas Scale apps (which is kubernetes based as far as I understood). double-take can connect to frigate (green dot), but not to deepstack (red dot).

**Version of Double Take**
`1.13.11`

**Expected behavior**
well obviously connect to deepstack.

**Screenshots**
![grafik](https://github.com/jakowenko/double-take/assets/12829391/075b66d0-c64b-411d-857f-44fb4b8d9904)
![grafik](https://github.com/jakowenko/double-take/assets/12829391/d8ce4e6c-78a8-432d-857d-a0c500e00aec)

**Hardware**
 - OS: TrueNAS Scale with Apps 
 - Browser (if applicable): Firefox, but I don't think it's browser related

**Additional context**
double-take logs:
```
24-01-11 07:08:08 error: Error: deepstack process error: write ECONNRESET
    at Function.AxiosError.from (/double-take/api/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/double-take/api/node_modules/axios/dist/node/axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:525:35)
    at ClientRequest.eventHandlers.<computed> (/double-take/api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
24-01-11 07:08:11 warn: unexpected deepstack data
24-01-11 07:08:12 error: Error: deepstack process error: write ECONNRESET
    at Function.AxiosError.from (/double-take/api/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/double-take/api/node_modules/axios/dist/node/axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:525:35)
    at ClientRequest.eventHandlers.<computed> (/double-take/api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
24-01-11 07:08:15 info: processing eingang: 41f45488-e392-49e6-9d06-a59b7a3a5846
24-01-11 07:08:15 error: Error: deepstack process error: write ECONNRESET
    at Function.AxiosError.from (/double-take/api/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/double-take/api/node_modules/axios/dist/node/axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:525:35)
    at ClientRequest.eventHandlers.<computed> (/double-take/api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
24-01-11 07:08:15 info: done processing eingang: 41f45488-e392-49e6-9d06-a59b7a3a5846 in 0.02 sec
24-01-11 07:08:15 info: {
  id: '41f45488-e392-49e6-9d06-a59b7a3a5846',
  duration: 0.02,
  timestamp: '2024-01-11T06:08:15.028Z',
  attempts: 1,
  camera: 'eingang',
  zones: [],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []
}
24-01-11 07:08:16 error: Error: deepstack process error: write ECONNRESET
    at Function.AxiosError.from (/double-take/api/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/double-take/api/node_modules/axios/dist/node/axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:525:35)
    at ClientRequest.eventHandlers.<computed> (/double-take/api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
24-01-11 07:08:18 warn: unexpected deepstack data
24-01-11 07:08:21 info: done processing Eingang: 1704953279.182421-ulx4kt in 6.17 sec
24-01-11 07:08:21 info: {
  id: '1704953279.182421-ulx4kt',
  duration: 6.17,
  timestamp: '2024-01-11T06:08:21.181Z',
  attempts: 18,
  camera: 'Eingang',
  zones: [],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []
}
24-01-11 07:08:22 info: done processing Eingang: 1704953279.182421-ulx4kt in 7.77 sec
24-01-11 07:08:22 info: {
  id: '1704953279.182421-ulx4kt',
  duration: 7.77,
  timestamp: '2024-01-11T06:08:22.779Z',
  attempts: 18,
  camera: 'Eingang',
  zones: [ 'Treppe' ],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []
}
```

**Comment by jkatsa** [comment]
Hello! I came here looking for an answer to a similar problem as you, but I believe I've just found a solution.

I'm currently using:
- TrueNAS-SCALE-23.10.1.3
- Double-Take (TrueCharts)
  - App Version: 1.13.11
  - Chart Version: 9.3.0
- DeepStack (TrueCharts)
  - App Version: 2022.01.1
  - Chart Version: 10.3.0

Since I'm using TrueCharts versions of these apps instead of the TrueNAS versions, I'll also note that I'm using the MetalLB to assign my apps their own static IPs.

To get the green dot for DeepStack in Double-Take, I did the following:
- Supplied the IP address of my DeepStack instance (with the port) without the trailing `/`
- Created an API key for DeepStack and supplied it when configuring the app (I just used VaultWarden to generate a random, long string)
- Added the API key to the Double-Take `secrets.yml` (my key in the `secrets.yml` isn't surrounded by quotation marks, if that helps)
- Supplied the API key in the Double-Take DeepStack configuration (I was receiving an error saying that the `key` property for the DeepStack configuration wasn't of type `string`, which is why I went back and configured an API key for DeepStack)

Hopefully that all makes sense. Here's the DeepStack snippet of my Double-Take configuration:

```yaml
detectors:
  deepstack:
    url: http://192.168.0.24:10049
    key: !secret double_take_deepstack_key
    timeout: 15
    opencv_face_required: false
```

Let me know if I can be of any assistance since we're in similar situations! Thanks very much!
