### ISSUE TITLE
[BUG] SqliteError: database disk image is malformed

### ISSUE THREAD

**Issue by jjvelar** [jakowenko/double-take#348]
Hi,
I get this error: SqliteError: database disk image is malformed
No images or training images are available.
Double-take (1.13.1) is installed in Home Assistant OS as an add-onn.
Please advise.
Thanks in advance for your help.

**Comment by bsdzip** [comment]
I got this too. Running in docker, connected to compreface and hass/mqtt.

info: Double Take v1.13.11.8
info: MQTT: connected
info: MQTT: subscribed to frigate/events
error: SqliteError: purge error: database disk image is malformed
    at Job.job (/double-take/api/src/util/storage.util.js:42:70)

Images was purged, but not the data.
After manually removing all matches, I was left with one that gives me "Request failed with status 500" and it could not be deleted.

Log when trying to delete:
error: SqliteError: database disk image is malformed
    at module.exports.delete (/double-take/api/src/controllers/match.controller.js:136:75)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:149:13)
    at /double-take/api/src/middlewares/index.js:67:3
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/double-take/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/double-take/api/node_modules/express/lib/router/route.js:149:13)
    at module.exports.jwt (/double-take/api/src/middlewares/index.js:9:14)
    at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)

I did try with sqlite3 PRAGMA  commands, but failed, these was the output:
sqlite> PRAGMA integrity_check;
row 1 missing from index idx_match_response_match
row 1 missing from index idx_match_filename
row 1 missing from index idx_match_createdAt
wrong # of entries in index idx_match_response_match
wrong # of entries in index idx_match_filename
wrong # of entries in index idx_match_createdAt

Ended up recreating the db:
sqlite3 database.db .dump > backup.sql
mv database.db old_database.db
sqlite3 database.db < backup.sql

All good, seems to be working now.
